[project]
name = "netdisk-mcp-server"
version = "0.1.0"
description = "百度网盘MCP Server，"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
    "mcp[cli]>=1.6.0",
    "python-dateutil>=2.9.0.post0",
    "urllib3>=1.25.3",
    "requests>=2.31.0",
]
